export interface Habitacion {
  nombre: string;
  imagenes: string[];
  items: string[];
}

export const HABITACIONES: Habitacion[] = [
  {
    nombre: 'Doble',
    imagenes: ['assets/rooms/doble/doble_01.jpg', 'assets/rooms/doble/doble_02.jpg', 'assets/rooms/doble/doble_03.jpg', 'assets/rooms/doble/doble_04.jpg'],
    items: [
      '13 habitaciones de 23 mt2.',
      'Cama Queen o Twin',
      'Se puede adicionar practicuna (sin cargo).',
      'Cama extra (con cargo).',
      'Smart TV 32".',
      'Direct TV.',
      'WI-FI (sin cargo).',
      'Calefacción central.',
      'Split frío/calor.',
      'Caja de seguridad.',
      'Bañera con agarraderas.',
      'Teléfono.',
      'Amenities.',
      'Desayuno incluido.',
      'Estacionamiento (sin cargo).',
      'Acceso libre a todas las instalaciones.',
    ],
  },
  {
    nombre: 'Triple',
    imagenes: [
      'assets/rooms/triple/triple_01.jpg',
      'assets/rooms/triple/triple_02.jpg',
      'assets/rooms/triple/triple_03.jpg',
      'assets/rooms/triple/triple_04.jpg',],
    items: [
      'Habitaciones de 25 mt2 y terraza de 12 mts2.',
      'Cama Queen + single.',
      'Se puede adicionar practicuna (sin cargo).',
      'Cama extra (con cargo).',
      'Smart TV 32".',
      'Direct TV.',
      'WI-FI (sin cargo).',
      'Calefacción central.',
      'Split frío/calor.',
      'Caja de seguridad.',
      'Bañera con agarraderas.',
      'Teléfono.',
      'Amenities.',
      'Frigobar.',
      'Desayuno incluido.',
      'Estacionamiento (sin cargo).',
      'Acceso libre a todas las instalaciones.',
    ],
  },
  {
    nombre: 'Cuádruple',
    imagenes: [
      'assets/rooms/cuadruple/cuadruple_01.jpg',
      'assets/rooms/cuadruple/cuadruple_02.jpg',
      'assets/rooms/cuadruple/cuadruple_03.jpg',
      'assets/rooms/cuadruple/cuadruple_04.jpg',],
    items: [
      'Superficie 43 mts2 más 6 mts2 terraza.',
      'Cama Queen + 2 singles.',
      'Se puede adicionar practicuna (sin cargo).',
      '1 Smart TV 32" y otro TV de 24".',
      'Direct TV.',
      'WI-FI (sin cargo).',
      'Calefacción central.',
      'Split frío/calor.',
      'Caja de seguridad.',
      'Bañera con agarraderas.',
      'Teléfono.',
      'Amenities.',
      'Frigobar.',
      'Desayuno incluido.',
      'Estacionamiento (sin cargo).',
      'Acceso libre a todas las instalaciones.',
    ],
  },
  {
    nombre: 'Cabaña',
    imagenes: ['assets/rooms/cabana/cabana_01.jpg'],
    items: [
      '80 mts cubiertos mas 55 mts con deck y parrillero.',
      'cuenta con 2 habitaciones.',
      'Ppal. con Cama Queen y sec. con 2 Twin.',
      'Cama Queen + singles.',
      'Se puede adicionar practicuna (sin cargo)',
      'Tv plana 50" en sala, Smart TV 32" en hab. ppal.',
      'Direct TV.',
      'WI-FI (sin cargo).',
      'Calefacción central.',
      'Split frío/calor.',
      'Caja de seguridad.',
      'Living Comedor.',
      'Cocina totalmente equipada.',
      'Microondas, pava eléctrica y vajilla.',
      'Heladera con freezer, anafe.',
      'Ducha y bañera con agarraderas.',
      'Teléfono.',
      'Amenities.',
      'Frigobar.',
      'Desayuno incluido.',
      'Estacionamiento (sin cargo).',
      'Acceso libre a todas las instalaciones.',
      'Chimenea.',
    ],
  },
  {
    nombre: 'Suite',
    imagenes: [
      'assets/rooms/suite/suite_01.jpg',
      'assets/rooms/suite/suite_02.jpg',
      'assets/rooms/suite/suite_03.jpg',
      'assets/rooms/suite/suite_04.jpg',
    ],
    items: [
      'Son 5 Suites Premium',
      '40 mts2 con decoración moderna.',
      'Baño y living, elegantes.',
      'Cama King o twin.',
      'Se puede adicionar practicuna(sin cargo).',
      'Cama extra con cargo.',
      'Smart TV 43".',
      'Direct TV.',
      'WI - FI(sin cargo).',
      'Calefacción central.',
      'Split frío / calor.',
      'Caja de seguridad.',
      'Ducha y bañera con agarraderas.',
      'Teléfono.',
      'Amenities.',
      'Frigobar y pava eléctrica.',
      'Terraza y galería con decks y sillones.',
      'Desayuno incluido.',
      'Estacionamiento(sin cargo).',
      'Acceso libre a todas las instalaciones.',
      'Escritorio.',
    ],
  },
  {
    nombre: 'Presidencial',
    imagenes: [
      'assets/rooms/suite/suite_01.jpg',
      'assets/rooms/suite/suite_02.jpg',
      'assets/rooms/suite/suite_03.jpg',
      'assets/rooms/suite/suite_04.jpg',
    ],
    items: [
      'Habitación, con deck privado y sillones.',
      'Vista a las sierras y al jardín.',
      'Cama King.',
      'Se puede adicionar practicuna (sin cargo).',
      'Cama extra (con cargo).',
      'Smart TV 43".',
      'Direct TV.',
      'WI-FI (sin cargo).',
      'Calefacción central.',
      'Split frío/calor.',
      'Caja de seguridad.',
      'Antebaño con bacha.',
      'Ducha y bañera con agarraderas de seguridad.',
      'Teléfono.',
      'Amenities.',
      'Frigobar y pava electrica.',
      'Galería y Palier privado con sillones.',
      'Desayuno incluido.',
      'Estacionamiento (sin cargo).',
      'Acceso libre a todas las instalaciones.',
      'Escritorio.',
    ],
  },
];
